using System;
using System.Collections.Generic;

namespace ProjectEuler
{
    class Program
    {
        static void Main(string[] args)
        {
            Program p = new Program();
            p.ProblemTwo();
            Console.ReadKey();
        }

        public void ProblemOne()
        {
            Console.WriteLine("If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\nFind the sum of all the multiples of 3 or 5 below 1000.");
            int Total = 0;
            for(int i = 1; i < 1000; i++)
            {
                if ((i % 3 == 0) || (i % 5 == 0))
                {
                    Total += i;
                }
            }
            Console.WriteLine(Total);
        }
        public void ProblemTwo()
        {
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
            List<int> Fibonacci = new List<int>
            {
                1,2
            };
            int n = 1;
            while (Fibonacci[n] < 4000000)
            {
                Fibonacci.Add(Fibonacci[n - 1] + Fibonacci[n]);
                n++;
            }
            int Total = 0;
            foreach (var interger in Fibonacci)
            {
                if (interger % 2 == 0)
                {
                    Total += interger;
                }
            }
            Console.WriteLine(Total);
        }
    }
}
